<?php

namespace Tainacan;

defined( 'ABSPATH' ) or die( 'No script kiddies please!' );

/**
 * Abstract base class for asynchronous requests.
 *
 * Provides the foundation for handling asynchronous HTTP requests
 * in WordPress, typically used for background processing tasks.
 *
 * @since 1.0.0
 * @abstract
 */
abstract class Async_Request {

	/**
	 * Request prefix for identifying the async request.
	 *
	 * @since 1.0.0
	 *
	 * @var string
	 */
	protected $prefix = 'wp';

	/**
	 * Action name for the async request.
	 *
	 * @since 1.0.0
	 *
	 * @var string
	 */
	protected $action = 'async_request';

	/**
	 * Unique identifier for this request.
	 *
	 * @since 1.0.0
	 *
	 * @var mixed
	 */
	protected $identifier;

	/**
	 * Data to be sent with the async request.
	 *
	 * @since 1.0.0
	 *
	 * @var array
	 */
	protected $data = array();

	/**
	 * Constructor for the Async_Request class.
	 *
	 * Initializes the async request with a unique identifier.
	 *
	 * @since 1.0.0
	 */
	public function __construct() {
		$this->identifier = $this->prefix . '_' . $this->action;

		add_action( 'wp_ajax_' . $this->identifier, array( $this, 'maybe_handle' ) );
		add_action( 'wp_ajax_nopriv_' . $this->identifier, array( $this, 'maybe_handle' ) );
	}

	/**
	 * Set data used during the request
	 *
	 * @param array $data Data.
	 *
	 * @return $this
	 */
	public function data( $data ) {
		$this->data = $data;

		return $this;
	}

	/**
	 * Dispatch the async request
	 *
	 * @return array|WP_Error
	 */
	public function dispatch() {
		$url  = add_query_arg( $this->get_query_args(), $this->get_query_url() );
		$args = $this->get_post_args();

		return wp_remote_post( esc_url_raw( $url ), $args );
	}

	/**
	 * Get query args
	 *
	 * @return array
	 */
	protected function get_query_args() {
		if ( property_exists( $this, 'query_args' ) ) {
			return $this->query_args;
		}

		return array(
			'action' => $this->identifier,
			'nonce'  => wp_create_nonce( $this->identifier ),
		);
	}

	/**
	 * Get query URL
	 *
	 * The dispatch mechanism sends an HTTP request back to this site
	 * (admin-ajax.php) to trigger the background process asynchronously.
	 * In some environments — notably Docker-based development stacks where
	 * the public `siteurl`/`home` option points at a host port (e.g.
	 * `http://localhost:8080`) that is not reachable from inside the
	 * container — the loopback request fails silently and the process
	 * never starts until WP-Cron eventually fires.
	 *
	 * To fix this, define `TAINACAN_BG_PROCESS_LOOPBACK_URL` in
	 * `wp-config.php` with an internally-reachable base URL (e.g.
	 * `http://localhost` inside the container). When set, the dispatch
	 * request targets that URL instead of `admin_url()`, while the rest
	 * of WordPress (REST API, admin pages, etc.) keeps using the public
	 * `siteurl`. This makes background processes dispatch immediately,
	 * without waiting for the WP-Cron schedule.
	 *
	 * @return string
	 */
	protected function get_query_url() {
		if ( property_exists( $this, 'query_url' ) ) {
			return $this->query_url;
		}

		// Allow an explicit loopback override for environments where the
		// public siteurl is not reachable from the server itself (Docker, etc.).
		if ( defined( 'TAINACAN_BG_PROCESS_LOOPBACK_URL' ) && TAINACAN_BG_PROCESS_LOOPBACK_URL ) {
			$base = rtrim( TAINACAN_BG_PROCESS_LOOPBACK_URL, '/' );
			return $base . '/wp-admin/admin-ajax.php';
		}

		/**
		 * Filters the query URL used to dispatch background processes.
		 *
		 * @param string $url The admin-ajax.php URL.
		 */
		return apply_filters( 'tainacan_background_process_query_url', admin_url( 'admin-ajax.php' ) );
	}

	/**
	 * Get post args
	 *
	 * The dispatch loopback request is sent to admin-ajax.php on this same
	 * server. Because maybe_handle() verifies a nonce via check_ajax_referer()
	 * — and WordPress nonces are tied to the logged-in user — the loopback
	 * request must carry the same user's authentication cookies as the
	 * request that queued the process. Without cookies, the loopback arrives
	 * as an unauthenticated (user 0) request and the nonce generated by the
	 * admin who queued the process fails validation, so the background
	 * process never starts until WP-Cron eventually fires.
	 *
	 * Forwarding the auth cookies makes the immediate dispatch work reliably
	 * in every environment (shared hosting, Docker, etc.).
	 *
	 * @return array
	 */
	protected function get_post_args() {
		if ( property_exists( $this, 'post_args' ) ) {
			return $this->post_args;
		}

		// Forward the current user's authentication cookies so the loopback
		// request is authenticated as the same user who generated the nonce.
		$cookies = array();
		foreach ( array( AUTH_COOKIE, SECURE_AUTH_COOKIE, LOGGED_IN_COOKIE ) as $cookie_name ) {
			if ( $cookie_name && isset( $_COOKIE[ $cookie_name ] ) ) {
				$cookies[] = new \WP_Http_Cookie( array(
					'name'  => $cookie_name,
					'value' => wp_unslash( $_COOKIE[ $cookie_name ] ),
				) );
			}
		}

		$args = array(
			'timeout'   => 10.00,
			'blocking'  => false,
			'body'      => $this->data,
			'sslverify' => apply_filters( 'https_local_ssl_verify', false ),
		);

		if ( ! empty( $cookies ) ) {
			$args['cookies'] = $cookies;
		}

		return $args;
	}

	/**
	 * Maybe handle
	 *
	 * Check for correct nonce and pass to handler.
	 */
	public function maybe_handle() {
		// Don't lock up other requests while processing
		session_write_close();

		check_ajax_referer( $this->identifier, 'nonce' );

		$this->handle();

		wp_die();
	}

	/**
	 * Handle
	 *
	 * Override this method to perform any actions required
	 * during the async request.
	 */
	abstract protected function handle();

}
