classDiagram
    direction TB
    class Exposer {
        #mappers : mixed
        +accept_no_mapper : mixed
        +slug : mixed
        -name : mixed
        -description : mixed
        #set_name(name)
        #set_description(description)
        +get_name()
        +get_description()
        +_toArray()
        +get_mappers()
    }
    class JSON_flat {
        +slug : mixed
        +name : mixed
        +accept_no_mapper : mixed
        #mappers : mixed
        +__construct()
        +rest_request_after_callbacks(response, handler, request)
    }
    Exposer <|-- JSON_flat
