classDiagram
    direction TB
    class Core_Description {
        +__construct()
        +get_form_labels()
        +form()
        +validate_options(metadatum)
        +get_value_as_html(item_metadata)
    }
