classDiagram
    direction TB
    class Textarea {
        +__construct()
        +get_form_labels()
        +get_multivalue_prefix()
        +get_multivalue_suffix()
        +get_value_as_html(item_metadata)
    }
