classDiagram
    direction TB
    class User {
        +__construct()
        +user_exists(user)
        +validate(item_metadata)
        +get_form_labels()
        +validate_options(metadatum)
        +get_value_as_html(item_metadata)
    }
