classDiagram
    direction TB
    class Elastic_Press {
        +last_aggregations : array
        +facets : array
        -aggregation_type : string
        -instance : Elastic_Press
        +$get_instance()
        #__construct(ajax_query)
        +is_active()
        +init()
        +prepare_meta_allowed_keys(allowed_keys)
        +modify_formatted_args(formatted_args)
        +elasticpress_config_mapping(mapping)
        +ep_post_sync_args(post_args, post_id)
        +filter_args(args, type)
        -add_items_args(args)
        +prepare_request(formatted_args, args)
        +format_aggregations(aggregations)
        +fetch_all_metadatum_values(return, metadatum, args)
        -prepare_request_for_items(formatted_args)
        -prepare_request_for_facet(formatted_args)
        -format_aggregations_items(aggregations)
        -format_aggregations_facet(aggregations)
    }
    Elastic_Press ..> Elastic_Press
