classDiagram
    direction TB
    class Roles {
        -capabilities : array
        -meta_caps : array
        -meta_section_caps : array
        -filters_caps : array
        -init()
        +populate_tainacan_capabilities()
        +get_tainacan_roles()
        +translate_user_roles(translations, text, context, domain)
        +get_all_caps()
        +get_collection_caps()
        +get_repository_caps()
        +get_all_caps_slugs()
        +get_collection_caps_slugs()
        +get_repository_caps_slugs()
        +init_default_roles()
        +get_cap_generic_name(cap)
        +user_has_cap_filter(allcaps, caps, args, user)
        +add_dependencies(role, cap)
        +map_meta_cap(caps, cap, user_id, args)
    }
