classDiagram
    direction TB
    class Theme_Helper {
        +visiting_collection_cover : mixed
        -registered_view_modes : mixed
        #default_placeholder_template : mixed
        -init()
        +is_post_type_a_collection(post_type)
        +is_post_an_item(post)
        +is_post_a_tainacan_taxonomy_postype(post)
        +is_taxonomy_a_tainacan_tax(tax_slug)
        +is_term_a_tainacan_term(term)
        +filter_archive_title(title)
        +override_item_single_template()
        +register_block_templates_for_item_single()
        +override_collection_items_archive_template()
        +register_block_templates_for_collection_items_archive()
        +override_taxonomy_term_items_archive_template()
        +override_repository_items_archive_template()
        +override_taxonomy_single_template()
        +permalink_filter(permalink, post, leavename)
        +tax_archive_pre_get_posts(wp_query)
        +collection_single_redirect()
        +item_template_hierarchy(templates)
        +collection_items_template_hierarchy(templates)
        +taxonomy_term_items_template_hierarchy(templates)
        +taxonomy_terms_template_hierarchy(templates)
        +header_image(image)
        +item_submission_shortcode(args)
        +get_tainacan_item_single_content()
        +search_shortcode(args)
        +get_tainacan_items_list(args, force_enqueue)
        +get_items_list_slug()
        +rewrite_rules(wp_rewrite)
        +rewrite_rules_query_vars(public_query_vars)
        +rewrite_rule_template_include(template)
        +archive_repository_pre_get_posts(wp_query)
        +register_view_mode(slug, args)
        +get_registered_view_modes()
        +get_view_mode(slug)
        +get_default_view_mode()
        +get_enabled_view_modes()
        +get_default_order()
        +get_default_orderby()
        +get_enable_item_link_query_params()
        +tainacan_get_collection_id()
        +tainacan_get_collection(args)
        +tainacan_get_item(post_id)
        +add_social_meta()
        +get_adjacent_items()
        +get_tainacan_items_carousel(args)
        +get_tainacan_dynamic_items_list(args)
        +get_tainacan_related_items_list(args)
        +get_tainacan_related_items_carousel(args)
        +get_tainacan_item_gallery(args)
        +get_tainacan_items_gallery(args)
        +get_tainacan_terms_carousel(args)
        +get_tainacan_item_metadata_template(args, collection_id)
        +get_tainacan_item_metadata_sections_template(args, collection_id)
        +get_metadata_section_template(metadata_section, args, section_index, collection_id)
        +get_tainacan_item_gallery_template(args)
        +get_taxonomies_query_args()
        +register_tainacan_oficial_view_modes()
        -convert_params_to_camel_case(params)
    }
    Theme_Helper ..> Theme_Helper
