classDiagram
    direction TB
    class Mapper {
        +slug : mixed
        +name : mixed
        +allow_extra_metadata : mixed
        +context_url : mixed
        +type : mixed
        +metadata : array
        +prefix : mixed
        +sufix : mixed
        +header : mixed
        +show_ui : mixed
        +_toArray()
        +get_url(meta_slug)
        +__construct()
    }
    class Dublin_Core {
        +slug : mixed
        +name : mixed
        +allow_extra_metadata : mixed
        +context_url : mixed
        +header : mixed
        +prefixes : mixed
        +XML_namespace : mixed
        +XML_append_root : mixed
        +__construct()
    }
    Mapper <|-- Dublin_Core
