classDiagram
    direction TB
    class Xml_Create {
        +doc : mixed
        +__construct(par_array)
        +addChild(mom_node, name, value)
        +addChildDC(mom_node, name, value)
        +create_request(par_array)
        +display()
    }
