classDiagram
    direction TB
    class Items {
        +entities_type : mixed
        -fetching_from_collections : mixed
        #init()
        #_get_map()
        +get_cpt_labels()
        +register_post_type()
        +insert(item)
        +fetch(args, collections, output)
        +fetch_ids(args, collections)
        +_filter_where(where, wp_query)
        +update(object, new_values)
        +generate_index_content(item)
        +get_thumbnail_id_from_document(item)
        +hook_api_updated_item(updated_item, attributes)
        +hook_comments_open(comments_open, post_id)
        +map_meta_cap(caps, cap, user_id, args)
        -get_related_items_by_collection(item, collection, metadata, args)
        +fetch_related_items(item, args)
        -parse_relationship_metaquery(args)
        +posts_where_relationship_metaquery(where)
        -parse_core_metadata_for_advanced_search(args, collections)
    }
    class Repository {
        +entities_type : string
        #use_logs : bool
        #logs_repository : Logs
        -map : array
        +disable_logs()
        +enable_logs()
        +get_enabled_logs()
        #__construct()
        +init_objects()
        +get_map()
        +get_name()
        +insert(obj)
        +insert_metadata(obj, prop, diffs)
        +maybe_add_slashes(value)
        +fetch_output(WP_Query, output)
        +parse_fetch_args(args)
        +get_default_properties(map)
        +get_mapped_property(entity, prop)
        +$get_collections_db_identifiers()
        +$get_entity_by_post(post)
        +$get_entity_by_post_type(post_type, post)
        +$get_repository(entity)
        +fetch_one(args)
        +trash(entity)
        +delete(entity, permanent)
        +can_edit(entity, user)
        +can_read(entity, user)
        +can_delete(entity, user)
        +can_publish(entity, user)
        +unique_multidimensional_array(array, key)
        -insert_thumbnail(obj, diffs)
        +get_descendants_ids(id, depth)
        +get_capabilities()
        #sanitize_value(content)
    }
    Repository ..> Items
    Repository ..> Repository
    Repository <|-- Items
