classDiagram
    direction TB
    class Logs {
        +entities_type : mixed
        -current_diff : mixed
        -current_deleting_entity : mixed
        -current_action : mixed
        #init()
        #_get_map()
        +register_post_type()
        +fetch(args, output)
        +update(object, new_values)
        +fetch_last()
        +insert_attachment(post_ID)
        +pre_delete_attachment(attachment_id)
        +delete_attachment(attachment_id)
        +pre_insert_entity(unsaved)
        -prepare_item_metadata_diff(unsaved)
        +__temporary_multivalue_separator(sep)
        +insert_entity(entity)
        +pre_delete_entity(entity, permanent)
        +delete_entity(entity, permanent)
        -insert_item_metadata(entity)
        +filter_log_title(title)
        +tainacan_set_log_slug(override, slug, post_ID, post_status, post_type, post_parent)
    }
    class Repository {
        +entities_type : string
        #use_logs : bool
        #logs_repository : Logs
        -map : array
        +disable_logs()
        +enable_logs()
        +get_enabled_logs()
        #__construct()
        +init_objects()
        +get_map()
        +get_name()
        +insert(obj)
        +insert_metadata(obj, prop, diffs)
        +maybe_add_slashes(value)
        +fetch_output(WP_Query, output)
        +parse_fetch_args(args)
        +get_default_properties(map)
        +get_mapped_property(entity, prop)
        +$get_collections_db_identifiers()
        +$get_entity_by_post(post)
        +$get_entity_by_post_type(post_type, post)
        +$get_repository(entity)
        +fetch_one(args)
        +trash(entity)
        +delete(entity, permanent)
        +can_edit(entity, user)
        +can_read(entity, user)
        +can_delete(entity, user)
        +can_publish(entity, user)
        +unique_multidimensional_array(array, key)
        -insert_thumbnail(obj, diffs)
        +get_descendants_ids(id, depth)
        +get_capabilities()
        #sanitize_value(content)
    }
    Logs ..> Repository
    Repository ..> Logs
    Repository ..> Repository
    Repository <|-- Logs
