classDiagram
    direction TB
    class Metadata_Sections {
        +entities_type : mixed
        #init()
        #_get_map()
        +get_cpt_labels()
        +register_post_type()
        +get_default_section(collection)
        +fetch(args, output)
        +fetch_ids(args)
        +fetch_by_collection(collection, args)
        +insert(metadata_section)
        +update(object, new_values)
        +add_metadata(metadata_section_id, metadata_list)
        +delete_metadata(metadata_section_id, metadata_list)
        +get_metadata_object_list(metadata_section_id, args)
        +get_default_section_metadata_object_list(collection, args)
        +delete(entity, permanent)
        +order_result(result, collection, include_disabled)
        +can_read(entity, user)
        +can_edit(entity, user)
    }
    class Repository {
        +entities_type : string
        #use_logs : bool
        #logs_repository : Logs
        -map : array
        +disable_logs()
        +enable_logs()
        +get_enabled_logs()
        #__construct()
        +init_objects()
        +get_map()
        +get_name()
        +insert(obj)
        +insert_metadata(obj, prop, diffs)
        +maybe_add_slashes(value)
        +fetch_output(WP_Query, output)
        +parse_fetch_args(args)
        +get_default_properties(map)
        +get_mapped_property(entity, prop)
        +$get_collections_db_identifiers()
        +$get_entity_by_post(post)
        +$get_entity_by_post_type(post_type, post)
        +$get_repository(entity)
        +fetch_one(args)
        +trash(entity)
        +delete(entity, permanent)
        +can_edit(entity, user)
        +can_read(entity, user)
        +can_delete(entity, user)
        +can_publish(entity, user)
        +unique_multidimensional_array(array, key)
        -insert_thumbnail(obj, diffs)
        +get_descendants_ids(id, depth)
        +get_capabilities()
        #sanitize_value(content)
    }
    Repository ..> Metadata_Sections
    Repository ..> Repository
    Repository <|-- Metadata_Sections
