classDiagram
    direction TB
    class Entity_Collection_Relation {
        #collection : mixed
        +get_collection_id()
        +get_collection()
        +set_collection_id(value)
        +set_collection(collection)
    }
