classDiagram
    direction TB
    class Exporter_Handler_Cell {
        +str_putcsv(input, delimiter, enclosure)
        +get_thumbnail_cell(item)
        +get_document_cell(item)
        +get_attachments_cell(item)
        +get_compound_metadata_cell(meta)
        +get_author_name_last_modification(item_id)
        +get_description_title_meta(meta)
    }
