classDiagram
    direction TB
    class Collection {
        #diplay_name : mixed
        +post_type : string
        #repository : string
        +db_identifier_prefix : string
        +db_identifier_sufix : string
        +__toString()
        +_toArray()
        +register_collection_item_post_type()
        +get_items_capabilities()
        +get_capabilities()
        +get_attachments(exclude)
        +get_author_name()
        +get_thumbnail()
        +get_header_image()
        +set__thumbnail_id(id)
        +get__thumbnail_id()
        +get_modification_date()
        +get_creation_date()
        +get_author_id()
        +get_url()
        +get_name()
        +get_slug()
        +get_order()
        +get_parent()
        +get_description()
        +get_default_order()
        +get_default_orderby()
        +get_default_displayed_metadata()
        +get_default_view_mode()
        +get_enabled_view_modes()
        +get_metadata_order()
        +get_metadata_section_order()
        +get_enable_cover_page()
        +get_header_image_id()
        +is_cover_page_enabled()
        +get_cover_page_id()
        +get_filters_order()
        +get_db_identifier()
        +get_metadata()
        +get_filters()
        +get_core_metadata()
        +get_core_title_metadatum()
        +get_core_description_metadatum()
        +get_comment_status()
        +get_allow_comments()
        +get_allow_item_slug_editing()
        +get_allow_item_author_editing()
        +get_submission_anonymous_user()
        +get_submission_default_status()
        +get_allows_submission()
        +get_hide_items_thumbnail_on_lists()
        +get_submission_use_recaptcha()
        +get_default_metadata_section_properties()
        +get_item_enabled_document_types()
        +get_item_publication_label()
        +get_item_document_label()
        +get_item_thumbnail_label()
        +get_item_enable_thumbnail()
        +get_item_attachment_label()
        +get_item_enable_attachments()
        +get_item_enable_metadata_focus_mode()
        +get_item_enable_metadata_required_filter()
        +get_item_enable_metadata_searchbar()
        +get_item_enable_metadata_collapses()
        +get_item_enable_metadata_enumeration()
        +set_name(value)
        +set_slug(value)
        +set_order(value)
        +set_parent(value)
        +set_description(value)
        +set_default_order(value)
        +set_default_orderby(value)
        +set_default_displayed_metadata(value)
        +set_default_view_mode(value)
        +set_enabled_view_modes(value)
        +set_metadata_order(value)
        +set_metadata_section_order(value)
        +set_filters_order(value)
        +set_enable_cover_page(value)
        +set_cover_page_id(value)
        +set_header_image_id(value)
        +set_comment_status(value)
        +set_allow_comments(value)
        +set_allow_item_author_editing(value)
        +set_allow_item_slug_editing(value)
        +set_submission_anonymous_user(value)
        +set_submission_default_status(value)
        +set_allows_submission(value)
        +set_hide_items_thumbnail_on_lists(value)
        +set_submission_use_recaptcha(value)
        +set_default_metadata_section_properties(value)
        +set_item_enabled_document_types(value)
        +set_item_publication_label(value)
        +set_item_document_label(value)
        +set_item_thumbnail_label(value)
        +set_item_enable_thumbnail(value)
        +set_item_attachment_label(value)
        +set_item_enable_attachments(value)
        +set_item_enable_metadata_focus_mode(value)
        +set_item_enable_metadata_required_filter(value)
        +set_item_enable_metadata_searchbar(value)
        +set_item_enable_metadata_collapses(value)
        +set_item_enable_metadata_enumeration(value)
        +validate()
        +user_can(capability, user)
    }
    class Entity {
        #repository : Repository
        -errors : array
        #post_type : string|false
        #capability_type : string|false
        +WP_Post : WP_Post
        -validated : bool
        +cap : object
        +__construct(which)
        +get_repository()
        +get_date_i18n(date)
        +get_mapped_property(prop)
        #set_mapped_property(prop, value)
        +set(prop, value)
        +get(prop)
        +set_status(value)
        +validate()
        +validate_prop(prop)
        +get_errors()
        +$get_post_type()
        +$get_capability_type()
        +get_status()
        +get_db_identifier()
        +get_id()
        +add_error(type, message)
        +reset_errors()
        +get_validated()
        #set_validated(value)
        #set_as_valid()
        +_toArray()
        +_toJson()
        +can_read(user)
        +can_edit(user)
        +can_delete(user)
        +can_publish(user)
        +get_capabilities()
        +diff(which)
    }
    Collection ..> Collection
    Entity ..> Collection
    Entity ..> Entity
    Entity <|-- Collection
