classDiagram
    direction TB
    class Item {
        #terms : mixed
        #repository : string
        +__construct(which)
        +__toString()
        +_toArray()
        +set_terms(value)
        +get_terms()
        +get_attachments(exclude)
        +get_author_name()
        +get_author_login()
        +get_thumbnail()
        +get_thumbnail_blurhash()
        +set__thumbnail_id(id)
        +get__thumbnail_id()
        +get_modification_date()
        +get_creation_date()
        +get_author_id()
        +get_url()
        +get_id()
        +get_title()
        +get_slug()
        +get_order()
        +get_parent()
        +get_description()
        +get_document_type()
        +get_document_options()
        +get_document_mimetype()
        +get_document()
        +get_db_identifier()
        +get_capabilities()
        +get_comment_status()
        +set_title(value)
        +set_slug(value)
        +set_order(value)
        +set_creation_date(value)
        +set_parent(value)
        +set_document_type(value)
        +set_document_options(value)
        +set_document(value)
        +set_description(value)
        +set_author_id(author_id)
        +get_metadata(args)
        #set_cap()
        +set_comment_status(value)
        +validate()
        +validate_core_metadata()
        +_toHtml()
        +get_metadata_as_html(args)
        +get_item_metadatum_as_html(item_metadatum, args, metadatum_index)
        +get_document_as_html(img_size)
        +get_attachment_as_html(attachment, img_size)
        +get_edit_url()
        +get_document_download_url()
        +get_related_items(args)
        +get_metadata_sections_as_html(args)
        +get_metadata_section_as_html(metadata_section, args, section_index)
    }
    class Entity {
        #repository : Repository
        -errors : array
        #post_type : string|false
        #capability_type : string|false
        +WP_Post : WP_Post
        -validated : bool
        +cap : object
        +__construct(which)
        +get_repository()
        +get_date_i18n(date)
        +get_mapped_property(prop)
        #set_mapped_property(prop, value)
        +set(prop, value)
        +get(prop)
        +set_status(value)
        +validate()
        +validate_prop(prop)
        +get_errors()
        +$get_post_type()
        +$get_capability_type()
        +get_status()
        +get_db_identifier()
        +get_id()
        +add_error(type, message)
        +reset_errors()
        +get_validated()
        #set_validated(value)
        #set_as_valid()
        +_toArray()
        +_toJson()
        +can_read(user)
        +can_edit(user)
        +can_delete(user)
        +can_publish(user)
        +get_capabilities()
        +diff(which)
    }
    Entity ..> Entity
    Entity ..> Item
    Entity <|-- Item
