classDiagram
    direction TB
    class Entity {
        #repository : Repository
        -errors : array
        #post_type : string|false
        #capability_type : string|false
        +WP_Post : WP_Post
        -validated : bool
        +cap : object
        +__construct(which)
        +get_repository()
        +get_date_i18n(date)
        +get_mapped_property(prop)
        #set_mapped_property(prop, value)
        +set(prop, value)
        +get(prop)
        +set_status(value)
        +validate()
        +validate_prop(prop)
        +get_errors()
        +$get_post_type()
        +$get_capability_type()
        +get_status()
        +get_db_identifier()
        +get_id()
        +add_error(type, message)
        +reset_errors()
        +get_validated()
        #set_validated(value)
        #set_as_valid()
        +_toArray()
        +_toJson()
        +can_read(user)
        +can_edit(user)
        +can_delete(user)
        +can_publish(user)
        +get_capabilities()
        +diff(which)
    }
    class Metadata_Section {
        +post_type : mixed
        +default_section_slug : mixed
        #name : mixed
        #repository : string
        +enabled_for_collection : mixed
        +__toString()
        +get_id()
        +get_name()
        +get_slug()
        +get_description()
        +get_description_bellow_name()
        +get_metadata_object_list(args)
        +get_is_conditional_section()
        +get_conditional_section_rules()
        +is_conditional_section()
        +set_name(value)
        +set_slug(value)
        +set_description(value)
        +set_description_bellow_name(value)
        +set_is_conditional_section(value)
        +set_conditional_section_rules(value)
        +get_enabled_for_collection()
        +set_enabled_for_collection(value)
        +validate()
    }
    Entity ..> Entity
    Entity <|-- Metadata_Section
