@startuml class-diagram
  class "Elastic_Press\n<b>Class Elastic_Press</b>" as Elastic_Press {
    +last_aggregations : array
    +facets : array
    -aggregation_type : string
    -instance : Elastic_Press
    {static} +get_instance()
    #__construct(ajax_query)
    +is_active()
    +init()
    +prepare_meta_allowed_keys(allowed_keys)
    +modify_formatted_args(formatted_args)
    +elasticpress_config_mapping(mapping)
    +ep_post_sync_args(post_args, post_id)
    +filter_args(args, type)
    -add_items_args(args)
    +prepare_request(formatted_args, args)
    +format_aggregations(aggregations)
    +fetch_all_metadatum_values(return, metadatum, args)
    -prepare_request_for_items(formatted_args)
    -prepare_request_for_facet(formatted_args)
    -format_aggregations_items(aggregations)
    -format_aggregations_facet(aggregations)
  }
  class "Elastic_Press_lte4" as Elastic_Press_lte4 {
    +last_aggregations : 
    +facets : 
    -aggregation_type : 
    -instance : 
    {static} +get_instance()
    #__construct(ajax_query)
    +is_active()
    +init()
    +elasticpress_config_mapping(mapping)
    +ep_post_sync_args(post_args, post_id)
    +filter_args(args, type)
    -add_items_args(args)
    +prepare_request(formatted_args, args)
    +format_aggregations(aggregations)
    +fetch_all_metadatum_values(return, metadatum, args)
    -prepare_request_for_items(formatted_args)
    -prepare_request_for_facet(formatted_args)
    -format_aggregations_items(aggregations)
    -format_aggregations_facet(aggregations)
  }
  class "WordPress_AI\n<b>Integration with the WordPress AI plugin (https://github.com/WordPress/ai).</b>" as WordPress_AI {
    #init()
    +is_active()
    +is_alt_text_generation_available()
    -is_alt_text_generation_usable()
    -has_vision_model_available()
  }
  Elastic_Press ..> Elastic_Press
  Elastic_Press ..> Elastic_Press_lte4
@enduml
