classDiagram
    direction TB
    class Admin_UI_Options { }
    class SVG_Icon { }
    class Singleton_Instance { }
    class Entity_Collections_Relation { }
    class Formatter_Text { }
    class Entity_Collection_Relation { }
