classDiagram
    direction TB
    class REST_Oaipmh_Expose_Controller { }
    class REST_Roles_Controller { }
    class REST_Metadata_Controller { }
    class REST_Exporters_Controller { }
    class REST_Items_Controller { }
    class REST_Metadata_Sections_Controller { }
    class REST_Background_Processes_Controller { }
    class REST_Reports_Controller { }
    class REST_Terms_Controller { }
    class REST_Metadata_Types_Controller { }
    class REST_Exposers_Controller { }
    class REST_Metadatum_Mappers_Controller { }
    class REST_Facets_Controller { }
    class REST_Filters_Controller { }
    class REST_Importers_Controller { }
    class REST_Collections_Controller { }
    class REST_Filter_Types_Controller { }
    class REST_Item_Metadata_Controller { }
    class REST_Bulkedit_Controller { }
    class REST_Taxonomies_Controller { }
    class REST_Logs_Controller { }
    class REST_Sequence_Edit_Controller { }
