@startuml class-diagram
  class "Collection\n<b>Represents a Tainacan Collection entity.</b>" as Collection {
    #diplay_name : 
    +post_type : string
    #repository : string
    +db_identifier_prefix : string
    +db_identifier_sufix : string
    +__toString()
    +_toArray()
    +register_collection_item_post_type()
    +get_items_capabilities()
    +get_capabilities()
    +get_attachments(exclude)
    +get_author_name()
    +get_thumbnail()
    +get_header_image()
    +set__thumbnail_id(id)
    +get__thumbnail_id()
    +get_modification_date()
    +get_creation_date()
    +get_author_id()
    +get_url()
    +get_name()
    +get_slug()
    +get_order()
    +get_parent()
    +get_description()
    +get_default_order()
    +get_default_orderby()
    +get_default_per_page()
    +get_default_displayed_metadata()
    +get_default_view_mode()
    +get_enabled_view_modes()
    +get_metadata_order()
    +get_metadata_section_order()
    +get_enable_cover_page()
    +get_header_image_id()
    +is_cover_page_enabled()
    +get_cover_page_id()
    +get_filters_order()
    +get_db_identifier()
    +get_metadata()
    +get_filters()
    +get_core_metadata()
    +get_core_title_metadatum()
    +get_core_description_metadatum()
    +get_comment_status()
    +get_allow_comments()
    +get_allow_item_slug_editing()
    +get_allow_item_author_editing()
    +get_submission_anonymous_user()
    +get_submission_default_status()
    +get_allows_submission()
    +get_hide_items_thumbnail_on_lists()
    +get_submission_use_recaptcha()
    +get_default_metadata_section_properties()
    +get_item_enabled_document_types()
    +get_item_publication_label()
    +get_item_document_label()
    +get_item_thumbnail_label()
    +get_item_enable_thumbnail()
    +get_item_attachment_label()
    +get_item_enable_attachments()
    +get_item_enable_metadata_focus_mode()
    +get_item_enable_metadata_required_filter()
    +get_item_enable_metadata_searchbar()
    +get_item_enable_metadata_collapses()
    +get_item_enable_metadata_enumeration()
    +get_item_enable_document_content_editing()
    +set_name(value)
    +set_slug(value)
    +set_order(value)
    +set_parent(value)
    +set_description(value)
    +set_default_order(value)
    +set_default_orderby(value)
    +set_default_per_page(value)
    +set_default_displayed_metadata(value)
    +set_default_view_mode(value)
    +set_enabled_view_modes(value)
    +set_metadata_order(value)
    +set_metadata_section_order(value)
    +set_filters_order(value)
    +set_enable_cover_page(value)
    +set_cover_page_id(value)
    +set_header_image_id(value)
    +set_comment_status(value)
    +set_allow_comments(value)
    +set_allow_item_author_editing(value)
    +set_allow_item_slug_editing(value)
    +set_submission_anonymous_user(value)
    +set_submission_default_status(value)
    +set_allows_submission(value)
    +set_hide_items_thumbnail_on_lists(value)
    +set_submission_use_recaptcha(value)
    +set_default_metadata_section_properties(value)
    +set_item_enabled_document_types(value)
    +set_item_publication_label(value)
    +set_item_document_label(value)
    +set_item_thumbnail_label(value)
    +set_item_enable_thumbnail(value)
    +set_item_attachment_label(value)
    +set_item_enable_attachments(value)
    +set_item_enable_metadata_focus_mode(value)
    +set_item_enable_metadata_required_filter(value)
    +set_item_enable_metadata_searchbar(value)
    +set_item_enable_metadata_collapses(value)
    +set_item_enable_metadata_enumeration(value)
    +set_item_enable_document_content_editing(value)
    +validate()
    +user_can(capability, user)
  }
  class "Term\n<b>Represents a Tainacan Term entity.</b>" as Term {
    +WP_Term : 
    #term_id : 
    +post_type : 
    #repository : string
    +__construct(which, taxonomy)
    +__toString()
    +_toArray()
    +get_id()
    +get_term_id()
    +get_name()
    +get_parent()
    +get_description()
    +get_user()
    +get_taxonomy()
    +get_header_image_id()
    +get_header_image()
    +get_url()
    +get_thumbnail()
    +get_thumbnail_blurhash()
    +set_name(value)
    +set_parent(value)
    +set_description(value)
    +set_user(value)
    +set_taxonomy(value)
    +set_header_image_id(value)
    +validate()
    +_toHtml()
  }
  class "Item\n<b>Represents a Tainacan Item entity.</b>" as Item {
    #terms : 
    #repository : string
    +__construct(which)
    +__toString()
    +_toArray()
    +set_terms(value)
    +get_terms()
    +get_attachments(exclude)
    +get_author_name()
    +get_author_login()
    +get_thumbnail()
    +get_thumbnail_blurhash()
    +set__thumbnail_id(id)
    +get__thumbnail_id()
    +get_modification_date()
    +get_creation_date()
    +get_author_id()
    +get_url()
    +get_id()
    +get_title()
    +get_slug()
    +get_order()
    +get_parent()
    +get_description()
    +get_document_type()
    +get_document_options()
    +get_document_content_index()
    +get_document_mimetype()
    +get_document()
    +get_db_identifier()
    +get_capabilities()
    +get_comment_status()
    +set_title(value)
    +set_slug(value)
    +set_order(value)
    +set_creation_date(value)
    +set_parent(value)
    +set_document_type(value)
    +set_document_options(value)
    +set_document_content_index(value)
    +set_document(value)
    +set_description(value)
    +set_author_id(author_id)
    +get_metadata(args)
    #set_cap()
    +set_comment_status(value)
    +validate()
    +validate_core_metadata()
    +_toHtml()
    +get_metadata_as_html(args)
    +get_item_metadatum_as_html(item_metadatum, args, metadatum_index)
    +get_document_as_html(img_size)
    +get_attachment_as_html(attachment, img_size)
    +get_edit_url()
    +get_document_download_url()
    +get_related_items(args)
    +get_metadata_sections_as_html(args)
    +get_metadata_section_as_html(metadata_section, args, section_index)
  }
  class "Log\n<b>Represents a Tainacan Log entity.</b>" as Log {
    #title : 
    +post_type : 
    #repository : string
    +__construct(which)
    +__toString()
    +_toArray()
    +get_capabilities()
    +set_collection_id(collection_id)
    +get_collection_id()
    +get_title()
    +get_user_name()
    +get_date()
    +get_slug()
    +get_description()
    +get_user_id()
    +get_old_value()
    +get_new_value()
    +set_title(value)
    +set_description(value)
    +set_user_id(value)
    +set_old_value(value)
    +set_new_value(value)
    +get_log_diffs()
    +get_object_type()
    +set_object_type(value)
    +get_object_id()
    +set_object_id(value)
    +set_item_id(item_id)
    +get_item_id()
    +get_action()
    +set_action(value)
    +approve()
  }
  class "Metadatum\n<b>Represents a Tainacan Metadatum entity.</b>" as Metadatum {
    #name : 
    +enabled_for_collection : 
    +post_type : 
    #capability_type : string
    #repository : string
    +__toString()
    +set_display(display)
    +get_display()
    +set_html_formatting(html_formatting)
    +get_html_formatting()
    +get_allow_advanced_search()
    +set_allow_advanced_search(allow_advanced_search)
    +get_name()
    +get_slug()
    +get_order()
    +get_parent()
    +get_description()
    +get_description_bellow_name()
    +get_placeholder()
    +get_required()
    +get_multiple()
    +get_cardinality()
    +get_collection_key()
    +get_default_value()
    +get_metadata_type_object()
    +get_metadata_type()
    +get_metadata_type_options()
    +get_accept_suggestion()
    +get_exposer_mapping()
    +get_semantic_uri()
    +get_metadata_section_id()
    +set_name(value)
    +set_slug(value)
    +set_order(value)
    +set_parent(value)
    +set_description(value)
    +set_description_bellow_name(value)
    +set_placeholder(value)
    +set_required(value)
    +set_multiple(value)
    +set_cardinality(value)
    +set_collection_key(value)
    +set_default_value(value)
    +set_metadata_type(value)
    +set_accept_suggestion(value)
    +set_metadata_type_options(value)
    +set_exposer_mapping(value)
    +set_semantic_uri(value)
    +set_metadata_section_id(value)
    +get_enabled_for_collection()
    +set_enabled_for_collection(value)
    +is_multiple()
    +is_collection_key()
    +is_required()
    +is_repository_level()
    +validate()
  }
  class "Filter\n<b>Represents a Tainacan Filter entity.</b>" as Filter {
    #name : 
    +post_type : 
    +enabled_for_collection : 
    #repository : string
    +__toString()
    +_toArray()
    +get_name()
    +get_description()
    +get_placeholder()
    +get_order()
    +get_max_options()
    +set_max_options(max_options)
    +get_metadatum_id()
    +get_metadatum()
    +get_filter_type_object()
    +get_filter_type()
    +get_filter_type_options()
    +get_begin_with_filter_collapsed()
    +get_display_in_repository_level_lists()
    +get_description_bellow_name()
    +set_name(value)
    +set_order(value)
    +set_description(value)
    +set_placeholder(value)
    +set_metadatum(value)
    +set_metadatum_id(value)
    +set_filter_type(value)
    +set_begin_with_filter_collapsed(begin_with_filter_collapsed)
    +set_display_in_repository_level_lists(display_in_repository_level_lists)
    +get_enabled_for_collection()
    +set_enabled_for_collection(value)
    +set_description_bellow_name(value)
    +validate()
    +set_filter_type_options(value)
  }
  class "Item_Metadata_Entity\n<b>Represents a Tainacan Item Metadata Entity.</b>" as Item_Metadata_Entity {
    #post_type : 
    #repository : string
    #item : 
    +__construct(item, metadatum, meta_id, parent_meta_id)
    +get_multivalue_prefix()
    +get_multivalue_suffix()
    +get_multivalue_separator()
    +get_value_as_html()
    +get_value_as_string()
    +get_value_as_array()
    +_toArray(formatted_values, cascade)
    +set_item(item)
    +set_value(value)
    +set_metadatum(metadatum)
    +set_meta_id(meta_id)
    +set_parent_meta_id(parent_meta_id)
    +get_item()
    +get_metadatum()
    +get_meta_id()
    +get_parent_meta_id()
    +get_value()
    +has_value()
    +is_multiple()
    +is_collection_key()
    +is_required()
    +validate()
  }
  class "Taxonomy\n<b>Represents a Tainacan Taxonomy entity.</b>" as Taxonomy {
    #name : 
    +post_type : string
    #capability_type : string
    #repository : string
    +db_identifier_prefix : string
    +__toString()
    +tainacan_register_taxonomy()
    +get_capabilities()
    +get_name()
    +get_description()
    +get_allow_insert()
    +get_hierarchical()
    +get_slug()
    +get_enabled_post_types()
    +get_db_identifier()
    +set_name(value)
    +set_slug(value)
    +set_description(value)
    +set_allow_insert(value)
    +set_hierarchical(value)
    +set_enabled_post_types(value)
    +validate()
    +term_exists(term_name, parent, return_term)
  }
  class "Entity\n<b>Abstract base class for all Tainacan entities.</b>" as Entity {
    #repository : Repository
    -errors : array
    #post_type : string|false
    #capability_type : string|false
    +WP_Post : WP_Post
    -validated : bool
    +cap : object
    +__construct(which)
    +get_repository()
    +get_date_i18n(date)
    +get_mapped_property(prop)
    #set_mapped_property(prop, value)
    +set(prop, value)
    +get(prop)
    +set_status(value)
    +validate()
    +validate_prop(prop)
    +get_errors()
    {static} +get_post_type()
    {static} +get_capability_type()
    +get_status()
    +get_db_identifier()
    +get_id()
    +add_error(type, message)
    +reset_errors()
    +get_validated()
    #set_validated(value)
    #set_as_valid()
    +_toArray()
    +_toJson()
    +can_read(user)
    +can_edit(user)
    +can_delete(user)
    +can_publish(user)
    +get_capabilities()
    +diff(which)
  }
  class "Metadata_Section\n<b>Represents a Tainacan Metadata Section entity.</b>" as Metadata_Section {
    +post_type : 
    +default_section_slug : 
    #name : 
    #repository : string
    +enabled_for_collection : 
    +__toString()
    +get_id()
    +get_name()
    +get_slug()
    +get_description()
    +get_description_bellow_name()
    +get_metadata_object_list(args)
    +get_is_conditional_section()
    +get_conditional_section_rules()
    +is_conditional_section()
    +set_name(value)
    +set_slug(value)
    +set_description(value)
    +set_description_bellow_name(value)
    +set_is_conditional_section(value)
    +set_conditional_section_rules(value)
    +get_enabled_for_collection()
    +set_enabled_for_collection(value)
    +validate()
  }
  Collection ..> Collection
  Collection ..> Metadatum
  Entity ..> Collection
  Entity ..> Entity
  Entity ..> Item
  Entity <|-- Collection
  Entity <|-- Filter
  Entity <|-- Item
  Entity <|-- Item_Metadata_Entity
  Entity <|-- Log
  Entity <|-- Metadata_Section
  Entity <|-- Metadatum
  Entity <|-- Taxonomy
  Entity <|-- Term
  Filter ..> Metadatum
  Item ..> Item_Metadata_Entity
  Item ..> Metadata_Section
  Item ..> Metadatum
  Item_Metadata_Entity ..> Item
  Item_Metadata_Entity ..> Item_Metadata_Entity
  Item_Metadata_Entity ..> Metadatum
  Item_Metadata_Entity ..> Term
  Metadatum ..> Metadata_Section
  Metadatum ..> Metadatum
@enduml
