classDiagram
    direction TB
    class JSON_LD { }
    class Exposer { }
    class JSON_flat { }
    class Csv { }
    class OAI_PMH { }
    class Txt { }
    class Xml { }
    class Exposers_Handler { }
    class Html { }
    Exposer <|-- Csv
    Exposer <|-- Html
    Exposer <|-- JSON_LD
    Exposer <|-- JSON_flat
    Exposer <|-- OAI_PMH
    Exposer <|-- Txt
    Exposer <|-- Xml
    Exposers_Handler ..> Exposer
    JSON_LD ..> Exposers_Handler
    Xml ..> Exposers_Handler
