@startuml class-diagram
  class "Youtube_Importer" as Youtube_Importer {
    #steps : 
    -items_repo : 
    +__construct(attributes)
    +get_source_metadata()
    +process_item(index, collection_definition)
    +identify_url(showDetails)
    +get_source_number_of_items()
    -get_list_items()
    +after_inserted_item(inserted_item, collection_index)
    +save_mapping(collection_id, mapping)
    +get_mapping(collection_id)
    +add_collection(collection)
    +options_form()
  }
  class "Test_Importer\n<b>Test Importer</b>" as Test_Importer {
    #steps : 
    #selectbox_values : 
    #date_values : 
    #numeric_values : 
    #text_values : 
    #textarea_values : 
    #extra_values : 
    #tax_repo : 
    #col_repo : 
    #items_repo : 
    #metadata_repo : 
    #item_metadata_repo : 
    +__construct(attributes)
    +options_form()
    +create_taxonomies()
    +create_collections()
    +link_relationship()
    +close_taxonomies()
    +finish_processing()
    +process_item(index, collection_definition)
    +after_inserted_item(inserted_item, collection_index)
    +get_col1_number_of_items()
    +get_col2_number_of_items()
    -create_metadata(args, collection)
    +get_col1_item(index)
    +get_col2_item(index)
  }
  class "Flickr_Importer" as Flickr_Importer {
    #endPoint : 
    #method : 
    #apiKey : 
    #perPage : 
    #format : 
    #apiKeyValue : 
    #steps : 
    -items_repo : 
    +__construct(attributes)
    +get_source_metadata()
    +process_item(index, collection_definition)
    +identify_url(showDetails)
    +get_source_number_of_items()
    -get_list_items()
    -process_item_user_request(items_json, index, collection_definition)
    -process_item_album_request(items_json, index, collection_definition)
    -process_item_single_request(items_json, index, collection_definition)
    -get_item_data(id)
    +after_inserted_item(inserted_item, collection_index)
    +save_mapping(collection_id, mapping)
    +get_mapping(collection_id)
    +add_collection(collection)
    -get_image_mime_type(image_path)
    +options_form()
  }
  class "Background_Importer" as Background_Importer {
    #action : string
    -finish_status : int
    +__construct()
    -set_finish_status(status)
    +task(batch)
  }
  class "Importer_Handler" as Importer_Handler {
    #bg_importer : Background_Importer
    -registered_importers : 
    -init()
    +register_importers()
    +add_to_queue(importer_object)
    +register_importer(importer)
    +unregister_importer(importer_slug)
    +get_registered_importers()
    +get_importer(importer_slug)
    +get_importer_by_object(importer_object)
    +initialize_importer(importer_slug)
    +save_importer_instance(importer)
    +get_importer_instance_by_session_id(session_id)
    +delete_importer_instance(importer)
  }
  class "Importer" as Importer {
    -id : identifier
    #tmp_file : string
    #collections : array
    -options : array
    #default_options : array
    -accepts : 
    #steps : array
    -transients : array
    -current_step : 
    -in_step_count : 
    -current_collection : 
    -current_collection_item : 
    -url : 
    -log : 
    -error_log : 
    -abort : bool
    -array_attributes : array
    +__construct(attributes)
    +_to_Array(short)
    +get_id()
    +set_url(url)
    +get_url()
    +get_current_step()
    +set_current_step(value)
    +get_in_step_count()
    +set_in_step_count(value)
    +get_current_collection()
    +set_current_collection(value)
    +get_current_collection_item()
    +set_current_collection_item(value)
    +get_tmp_file()
    +set_tmp_file(filepath)
    +get_collections()
    +set_collections(value)
    +get_options()
    +set_options(options)
    #set_default_options(options)
    +set_steps(steps)
    +get_steps()
    -get_transients()
    -set_transients(data)
    +get_log()
    +get_error_log()
    +add_file(file)
    +add_log(message)
    +add_error_log(message)
    +add_collection(collection)
    +remove_collection(col_id)
    -upload_file(file_array)
    +fetch_from_remote(url)
    +get_option(key)
    +add_import_method(method)
    +remove_import_method(method)
    +add_transient(key, data)
    +delete_transient(key)
    +get_transient(key)
    +is_finished()
    #cancel_abort()
    #abort()
    +get_abort()
    +get_progress_label()
    +get_progress_value()
    #set_current_step_total(value)
    #set_step_total(step, value)
    +get_source_metadata()
    {abstract} +process_item(index, collection_id)
    +get_source_number_of_items()
    +options_form()
    +get_output()
    +process_collections()
    #next_item()
    #next_collection()
    #next_step()
    +insert(processed_item, collection_index)
    +after_inserted_item(insertedItem, collection_index)
    +run()
    +create_new_metadata(metadata_description, collection_id, parent_id)
  }
  class "Term_Importer" as Term_Importer {
    #steps : 
    +__construct(attributes)
    #open_tmp_file()
    +options_form()
    +process_item(index, collection_definition)
    +create_terms()
    +create_taxonomy()
    +get_output()
  }
  class "Oaipmh_Importer" as Oaipmh_Importer {
    #steps : 
    #NAME_FOR_SETS : 
    #tainacan_api_address : 
    #has_sets : 
    #items_per_page : 
    -col_repo : 
    -items_repo : 
    -metadata_repo : 
    -item_metadata_repo : 
    -tax_repo : 
    -term_repo : 
    +__construct(attributes)
    +process_item(index, collection_id)
    +create_collections()
    +insert(processed_item, collection_index)
    #get_identifier(metadata)
    +get_total_items_from_source(setSpec)
    #create_collection(setSpec, setName)
    #create_collection_metadata(collection_object)
    #fetch_collections()
    #decode_request(result, url)
    #requester(link)
    +createTerms(taxonomy_father, name, slug)
    +create_set_metadata(collection_id, taxonomy_id)
    +getRepoName()
    +hasCompleteSize(attributes)
    +get_progress_value()
    +options_form()
  }
  class "CSV" as CSV {
    -items_repo : 
    +__construct(attributes)
    #open_tmp_file()
    +set_option(key, value)
    +get_source_metadata()
    +get_source_file_name()
    +get_source_special_fields()
    +raw_source_metadata()
    +process_item(index, collection_definition)
    +after_inserted_item(inserted_item, collection_index)
    +get_source_number_of_items()
    +options_form()
    -handle_encoding(string)
    -handle_document(column_value, item_inserted)
    -handle_thumbnail(column_value, item_inserted)
    -handle_attachment(column_value, item_inserted)
    -handle_enclosure(file)
    -handle_item_status(status, item_inserted)
    -handle_item_comment_status(comment_status, item_inserted)
    -handle_item_author_id(author, item_inserted)
    -handle_item_slug(slug, item_inserted)
    -handle_item_id(values)
    +insert(processed_item, collection_index)
    -is_assoc(arr)
    -deleteAllValuesCompoundItemMetadata(item, compoundMetadataID)
    +is_empty_value(value)
    -is_clear_value(value)
    -insert_hierarchy(metadatum, values)
    +save_mapping(collection_id, mapping)
    +get_mapping(collection_id)
    +add_collection(collection)
    -get_collections_names()
    +get_output()
    -delete_previous_document_imgs(item_id, item_document)
  }
  Importer ..> Importer_Handler
  Importer <|-- CSV
  Importer <|-- Flickr_Importer
  Importer <|-- Oaipmh_Importer
  Importer <|-- Term_Importer
  Importer <|-- Test_Importer
  Importer <|-- Youtube_Importer
  Importer_Handler ..> Background_Importer
  Importer_Handler ..> Importer
@enduml
