classDiagram
    direction TB
    class Cli { }
    class Theme_Helper { }
    class Gutenberg_Blocks { }
    class Exposers_Handler { }
    class Cli_Document { }
    class Media { }
    class __Bulk_Edit { }
    class Pdf_Extracted_Text_Quality { }
    class Roles_Editor { }
    class Settings { }
    class Dashboard { }
    class Background_Process_Base { }
    class Async_Request { }
    class Pages { }
    class Cli_Collection { }
    class Cli_Control_Metadata { }
    class Admin { }
    class Private_Files { }
    class Background_Process { }
    class Cli_Move_Attachments { }
    class Cli_Garbage_Collector { }
    class Background_Process_Heartbeat { }
    class Search_Engine { }
    class Admin_Commands { }
    class Admin_Bar_Items { }
    class Logs_Wp_Posts_Migration { }
    class Cli_Logs { }
    class Mappers_Handler { }
    class Embed { }
    class System_Check { }
    class Mobile_App { }
    Async_Request <|-- Background_Process_Base
    Background_Process_Base <|-- Background_Process
    Cli_Logs ..> Logs_Wp_Posts_Migration
    Cli_Move_Attachments ..> Private_Files
    Cli_Move_Attachments ..> Theme_Helper
    Exposers_Handler ..> Mappers_Handler
    Gutenberg_Blocks ..> Admin
    Gutenberg_Blocks ..> Theme_Helper
    Media ..> Embed
    Media ..> Pdf_Extracted_Text_Quality
    Pages ..> Exposers_Handler
    Pages ..> Mappers_Handler
    Pages ..> Media
    Pages ..> Theme_Helper
    Pages <|-- Admin
    Pages <|-- Dashboard
    Pages <|-- Mobile_App
    Pages <|-- Roles_Editor
    Pages <|-- Settings
    Pages <|-- System_Check
    Private_Files ..> Media
    Private_Files ..> Theme_Helper
    Settings ..> Gutenberg_Blocks
    Settings ..> Media
    System_Check ..> Private_Files
    Theme_Helper ..> Mappers_Handler
    Theme_Helper ..> Theme_Helper
