classDiagram
    direction TB
    class Mapper { }
    class Inbcm_Museological { }
    class Dublin_Core { }
    class Inbcm_Archive { }
    class Mappers_Handler { }
    class Inbcm_Bibliographic { }
    Mapper <|-- Dublin_Core
    Mapper <|-- Inbcm_Archive
    Mapper <|-- Inbcm_Bibliographic
    Mapper <|-- Inbcm_Museological
    Mappers_Handler ..> Mapper
