classDiagram
    direction TB
    class GeoCoordinate_Helper {
        +posts_join : mixed
        +filter_where : mixed
        +init()
        +init_filters()
        +posts_join(join, wp_query)
        +posts_where(where, wp_query)
    }
