classDiagram
    direction TB
    class REST_Oaipmh_Expose_Controller {
        +__construct()
        +init_objects()
        +register_routes()
        +get_verb_permissions_check(request)
        +get_verb(request)
        +get_verb_params()
        +get_schema()
    }
