classDiagram
    direction TB
    class REST_Filter_Types_Controller {
        +__construct()
        +register_routes()
        +prepare_item_for_response(item, request)
        +get_items(request)
        +get_items_permissions_check(request)
        +get_schema()
    }
