classDiagram
    direction TB
    class REST_Roles_Controller {
        +__construct()
        +register_routes()
        +create_item(request)
        +create_item_permissions_check(request)
        +delete_item(request)
        +delete_item_permissions_check(request)
        +update_item(request)
        -handle_capabilities_for_role(role_slug, newcaps)
        -handle_capabilites_default_for_role(role_slug)
        +update_item_permissions_check(request)
        +validate_roles_capabilities_arg(value, request, param)
        +_prepare_item_for_response(slug, name, caps, request)
        +get_items(request)
        +get_items_permissions_check(request)
        +get_item(request)
        +get_item_permissions_check(request)
        +get_capabilities_permissions_check(request)
        +get_endpoint_args(method)
        +get_capabilities(request)
        +get_admin_ui_options(request)
        +update_admin_ui_options(request)
        +get_admin_ui_options_permissions_check(request)
        +update_admin_ui_options_permissions_check(request)
        +get_capabilities_schema()
        +get_schema()
        +get_admin_ui_options_schema()
    }
