classDiagram
    direction TB
    class REST_Importers_Controller {
        #get_schema()
        +__construct()
        +register_routes()
        +import_permissions_check(request)
        +create_item(request)
        +update_item(request)
        +source_info(request)
        +get_saved_mapping(request)
        +get_item(request)
        +add_file(request)
        +run(request)
        +get_registered_importers()
    }
