<?php

use Tainacan\Repositories;
use Tainacan\Entities;

class TAINACAN_REST_Items_Controller extends WP_REST_Controller {
	private $items_repository;
	private $item;

	public function __construct() {
		$this->namespace = 'tainacan/v2';
		$this->rest_base = 'items';
		$this->items_repository = new Repositories\Items();
		$this->item = new Entities\Item();

		add_action('rest_api_init', array($this, 'register_routes'));
	}

	public function register_routes() {
		register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/collection/(?P<collection_id>[\d]+)',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array($this, 'get_items'),
					//'permission_callback' => array($this, 'get_items_permissions_check'),
					'args'                => $this->get_collection_params(),
				),
				array(
					'methods'             => WP_REST_Server::CREATABLE,
					'callback'            => array($this, 'create_item'),
					'permission_callback' => array($this, 'create_item_permissions_check'),
					'args'                => $this->get_endpoint_args_for_item_schema(WP_REST_Server::CREATABLE),
				),
				'schema' => array($this, 'get_public_item_schema'),
		));
		register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/collection/(?P<collection_id>[\d]+)/(?P<item_id>[\d]+)',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array($this, 'get_item'),
					'permission_callback' => array($this, 'get_item_permissions_check'),
				),
				array(
					'methods'             => WP_REST_Server::EDITABLE,
					'callback'            => array($this, 'update_item'),
					'permission_callback' => array($this, 'update_item_permissions_check'),
				),
				array(
					'methods'             => WP_REST_Server::DELETABLE,
					'callback'            => array($this, 'delete_item'),
					'permission_callback' => array($this, 'delete_item_permissions_check'),
				),
		));
	}

	public function get_items( $request ) {
		return parent::get_items( $request ); // TODO: Change the autogenerated stub
	}

	public function get_item_permissions_check( $request ) {
		return parent::get_item_permissions_check( $request ); // TODO: Change the autogenerated stub
	}

	public function create_item( $request ) {
		return parent::create_item( $request ); // TODO: Change the autogenerated stub
	}

	public function create_item_permissions_check( $request ) {
		return parent::create_item_permissions_check( $request ); // TODO: Change the autogenerated stub
	}
}

?>