<?php

use Tainacan\Repositories;

class TAINACAN_REST_Collections_Controller extends WP_REST_Controller {
    private $collections_respository;

    public function __construct(){
        $this->namespace = 'tainacan/v2';
        $this->rest_base = 'collections';
        $this->collections_respository = new Repositories\Collections();

        add_action('rest_api_init', array($this, 'register_routes'));
    }

    public function register_routes(){
        register_rest_route($this->namespace, '/' . $this->rest_base, array(
            array(
                'methods'             => WP_REST_Server::READABLE,
                'callback'            => array($this, 'get_items'),
                //'permission_callback' => array($this, 'get_items_permission_check'),
            ),
        ));
        register_rest_route($this->namespace, '/' . $this->rest_base . '/(?P<id>[\d]+)', array(
            array(
                'methods' => WP_REST_Server::READABLE,
                'callback' => array($this, 'get_item'),
                //'permission_callback' => array($this, 'get_item_permission_check'),
            ),
        ));
    }

    public function get_items($request){
        $collections = $this->collections_respository->fetch();

        $response = $this->prepare_item_for_response($collections, $request);

        return new WP_REST_Response($response, 200);
    }

    public function get_item($request){
        $collection_id = $request['id'];
        $collection = $this->collections_respository->fetch($collection_id);

        $response = $this->prepare_item_for_response($collection, $request);

        return new WP_REST_Response($response, 200);
    }

    public function prepare_item_for_response($item, $request){
        if(is_array($item)){

            $collections_as_json = [];
            foreach ($item as $wp_post){
                array_push($posts_as_json, $wp_post->__toJSON());
            }

            return $collections_as_json;
        }
        else {
            return $item->__toJSON();
        }
    }

    public function get_item_schema(){

    }

    public function get_items_permissions_check($request){
        return parent::get_items_permissions_check($request); // TODO: Change the autogenerated stub
    }

    public function  get_item_permissions_check($request){
        return parent::get_item_permissions_check($request); // TODO: Change the autogenerated stub
    }
}

?>