<?php

use Tainacan\Entities;
use Tainacan\Repositories;

class TAINACAN_REST_Taxonomies_Controller extends WP_REST_Controller {
	private $taxonomy;
	private $taxonomy_repository;

	public function __construct() {
		$this->namespace = 'tainacan/v2';
		$this->rest_base = 'taxonomies';

		$this->taxonomy = new Entities\Taxonomy();
		$this->taxonomy_repository = new Repositories\Taxonomies();

		add_action('rest_api_init', array($this, 'register_routes'));
	}

	public function register_routes() {
		register_rest_route(
			$this->namespace, '/' . $this->rest_base,
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array($this, 'get_items'),
					'permission_callback' => array($this, 'get_items_permissions_check'),
				),
				array(
					'methods'             => WP_REST_Server::CREATABLE,
					'callback'            => array($this, 'create_item'),
					'permission_callback' => array($this, 'create_item_permissions_check'),
				)
			)
		);
		register_rest_route(
			$this->namespace, '/' . $this->rest_base . '/(?P<taxonomy_id>[\d]+)',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'callback'            => array($this, 'get_item'),
					'permission_callback' => array($this, 'get_item_permissions_check'),
				),
				array(
					'methods'             => WP_REST_Server::DELETABLE,
					'callback'            => array($this, 'delete_item'),
					'permission_callback' => array($this, 'delete_item_permissions_check'),
				)
			)
		);
	}

	public function prepare_item_for_response( $item, $request ) {
		$taxonomies = [];

		if($request['taxonomy_id']){
			return $item->__toArray();
		}

		foreach ( $item as $it ) {
			$taxonomies[] = $it->__toArray();
		}

		return $taxonomies;
	}

	public function prepare_item_for_database( $request ) {
		foreach ($request as $key => $value){
			$set_ = 'set_' . $key;
			$this->taxonomy->$set_($value);
		}
	}

	public function get_item( $request ) {
		$taxonomy_id = $request['taxonomy_id'];

		$taxonomy = $this->taxonomy_repository->fetch($taxonomy_id);

		$taxonomy_prepared = $this->prepare_item_for_response($taxonomy, $request);

		return new WP_REST_Response($taxonomy_prepared, 200);
	}

	public function get_item_permissions_check( $request ) {
		if(current_user_can('read')){
			return true;
		}

		return false;
	}

	public function delete_item( $request ) {
		return parent::delete_item( $request ); // TODO: Change the autogenerated stub
	}

	public function delete_item_permissions_check( $request ) {
		if (current_user_can('delete_posts')){
			return true;
		}

		return false;
	}

	public function get_items( $request ) {
		$taxonomies = $this->taxonomy_repository->fetch([], 'OBJECT');

		$taxonomies_prepared = $this->prepare_item_for_response($taxonomies, $request);

		return new WP_REST_Response($taxonomies_prepared, 200);
	}

	public function get_items_permissions_check( $request ) {
		if (current_user_can('read')){
			return true;
		}

		return false;
	}

	public function create_item( $request ) {
		$body = json_decode($request->get_body(), true);

		if(!empty($body)){
			$this->prepare_item_for_database($body);

			if($this->taxonomy->validate()){
				$taxonomy = $this->taxonomy_repository->insert($this->taxonomy);

				return new WP_REST_Response($taxonomy->__toArray(), 201);
			} else {
				return new WP_REST_Response([
					'error_message' => __('One or more values are invalid.', 'tainacan'),
					'errors'        => $this->taxonomy->get_errors(),
					'item_metadata' => $this->taxonomy->__toArray(),
				], 400);
			}
		} else {
			return new WP_REST_Response([
				'error_message' => __('Body can not be empty.', 'tainacan'),
			], 400);
		}
	}

	public function create_item_permissions_check( $request ) {
		if(current_user_can('edit_posts')){
			return true;
		}

		return false;
	}

}

?>