describe('TextArea field test', function() {
  beforeEach(() => {
    cy.loginByUI()
  })

  it('clear DB', function(){
    cy.clearDB()
  })

  it('create collection for create fields', function(){
    cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
    cy.get('h1').should('contain', 'Collections Page')
    cy.get('#button-collection-creation').click()
    cy.get('#tainacan-text-name').type('TextArea Fields')
    cy.get('#tainacan-text-description').type('Description TextArea Fields')
    cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
    cy.get('#button-submit-collection-creation').click()
    cy.get('#primary-menu > .menu > .menu-header > .menu-list > li > .router-link-active > .icon > .mdi').click()
    cy.get('.b-table').should('contain', 'TextArea Fields')
  })

  context('CRUD textArea field', function(){
    it('create model field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Model')
      cy.get('.textarea').type('description model')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'Model')
    })

    it('check create model field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.contains('Model')
    })

    it('create color field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Color')
      cy.get('.textarea').type('description color')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'Color')
    })

    it('check create color field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.contains('Color')
    })

    it('edit color field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(4) > .handle > .controls > :nth-child(2) > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type(' edited')
      cy.get('.textarea').type(' edited')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'Color edited')
    })

    it('create door field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Door')
      cy.get('.textarea').type('description door')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'Door')
    })

    it('delete door field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.contains('Door')
      cy.get(':nth-child(5) > .handle > .controls > :nth-child(3) > .icon > .mdi').click()
      cy.get('.handle > .field-name').should('not.eq', 'Door')
    })

    it('check not contain door field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.handle > .field-name').should('not.eq', 'Door')
    })
  })

  context('Diseble textArea field', function(){
    it('create motor field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Motor disebled')
      cy.get('.textarea').type('description motor')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'Motor disebled')
    })

    it('disebled motor field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(5) > .handle > .controls > .switch > .check').click()
      cy.get('.active-fields-area > :nth-child(5)').should('have.class', 'disabled-field')
      })

    it('check disebled motor field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.active-fields-area > :nth-child(5)').should('have.class', 'disabled-field')
    })
  })

  context('Check required fields', function(){
    it('create blank field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('.not-focusable-item > .handle > .label-details').should('contain', 'Not saved')
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Bank{selectall}{del}')
      cy.get('.textarea').clear()
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.not-focusable-item > .handle > .field-name').should('have.class', 'is-danger')
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').should('have.class', 'is-danger')
      cy.get(':nth-child(1) > .button').click()
      cy.get('.active-fields-area > :nth-child(6) > .handle > .field-name').should('not.contain', 'Blank').and('contain', 'Textarea')
      cy.get('.active-fields-area > :nth-child(6) > .handle > .label-details').should('contain', 'Not saved')
    })

    it('check not contain blank field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.active-fields-area').should('not.contain', 'Blank')
    })
  })

  context('Create textArea field private', function(){
    it('create private field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea Private')
      cy.get('.textarea').type('description private')
      cy.get('#tainacan-select-status-private > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'TextArea Private')
    })

    it('check create private field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.active-fields-area > :nth-child(6) > .handle > .field-name').should('contain', 'TextArea Private')
      cy.get(':nth-child(6) > .handle > .controls > :nth-child(2) > .icon > .mdi').click()
      cy.get('#tainacan-select-status-private > .check').should('be.selected')
    })
  })

  context('"Not saved" label vs. "cancel button"', function(){
    it('create brand field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Brand')
      cy.get('.textarea').type('description brand')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'Brand')
    })

    it('check that ‘Not Saved’ label wasn’t inserted, and changes were lost', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.active-fields-area > :nth-child(7) > .handle > .field-name').should('contain', 'Brand')
      cy.get(':nth-child(7) > .handle > .controls > :nth-child(2) > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type(' edited')
      cy.get('.textarea').type(' edited')
      cy.get('#tainacan-select-status-private > .check').click()
      cy.get(':nth-child(1) > .button').click()
      cy.get('.active-fields-area >').should('not.contain', 'Brand edited')
      cy.get('.active-fields-area > :nth-child(7) > .handle > .label-details').should('not.contain', 'Not saved')
    })

    it('check if the message “Not Saved” appeared next to the field name', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Steering Type')
      cy.get('.textarea').type('description new')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(1) > .button').click()
      cy.get('.active-fields-area > :nth-child(8) > .handle > .field-name').should('not.contain', 'Steering Type').and('contain', 'Textarea')
      cy.get('.active-fields-area > :nth-child(8) > .handle > .label-details').should('contain', 'Not saved')
      cy.get(':nth-child(8) > .handle > .controls > :nth-child(2) > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Steering Type')
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area > :nth-child(8) > .handle > .field-name').should('contain', 'Steering Type').and('not.contain', 'Textarea')
      cy.get('.active-fields-area > :nth-child(8) > .handle > .label-details').should('not.contain', 'Not saved')
    })
  })

  context('Fields Sorting', function(){
  })

  context('create textArea-types fields tests', function(){
    it('canceled create textArea field', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea name canceled')
      cy.get('.textarea').type('description')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(1) > .button').click()
      cy.get('.active-fields-area >').should('not.contain', 'TextArea name canceled')
    })

    it('create textArea-type field public required', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea name public required')
      cy.get('.textarea').type('book description required')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .b-checkbox > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'TextArea name public required')
    })

    it('create textArea-type field public multiple values', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea name public multiple values')
      cy.get('.textarea').type('book description multiple values')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(3) > .b-checkbox > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'TextArea name public multiple values')
    })

    it('create textArea-type field public unique values', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea name public unique values')
      cy.get('.textarea').type('name book description multiple values')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(4) > .b-checkbox > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.get('.active-fields-area >').should('contain', 'TextArea name public unique values')
    })
  })

  context('Leave page without saving field editions', function(){
    it('Leave page without saving field editions', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}Not Saved')
      cy.get('.textarea').type('description')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.contains('Items').click()
      cy.get('.modal-card').should('have.class', 'animation-content')
      cy.get('.modal-card-foot > :nth-child(1)').click()
      cy.get(':nth-child(1) > .button').click()
      cy.get('.active-fields-area >').should('not.contain', 'Not Saved').and('contain', 'TextArea')
      cy.get('.menu > :nth-child(2) > :nth-child(8) > a').click()
      cy.get('.modal-card').should('have.class', 'is-titleless')
    })
  })

  context('Field loading for paging and persistence testing', function(){
    it('create textAreas fields', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 1')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 2')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 3')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 4')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 5')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 6')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 7')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 8')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 9')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
      cy.wait(500)
      cy.get('.field > :nth-child(2) > :nth-child(2)').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('{selectall}{del}TextArea 10')
      cy.get('.textarea').type('description textArea')
      cy.get('#tainacan-select-status-publish > .check').click()
      cy.get(':nth-child(2) > .button').click()
    })

    it('check if fields are updated to page', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get(':nth-child(4) > .router-link-active').should('contain', 'Items')
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get('.active-fields-area >').should('contain', 'Model')
      .and('contain', 'Color edited')
      .and('contain', 'Motor disebled')
      .and('contain', 'TextArea Private')
      .and('not.contain', 'Blank')
      .and('contain', 'Brand')
      .and('contain', 'Steering Type')
      .and('not.contain', 'TextArea name canceled')
      .and('contain', 'TextArea name public required')
      .and('contain', 'TextArea name public multiple values')
      .and('contain', 'TextArea name public unique values')
      .and('contain', 'TextArea 1')
      .and('contain', 'TextArea 2')
      .and('contain', 'TextArea 3')
      .and('contain', 'TextArea 4')
      .and('contain', 'TextArea 5')
      .and('contain', 'TextArea 6')
      .and('contain', 'TextArea 7')
      .and('contain', 'TextArea 8')
      .and('contain', 'TextArea 9')
      .and('contain', 'TextArea 10')
    })
  })
})
